/*
 * GifMain.java
 *
 * Created on January 10, 2001, 5:23 PM
 */


/**
 *
 * @author  Bryan
 * @version
 */
public class GifMain extends javax.swing.JFrame {
    
    /** Creates new form GifMain */
    public GifMain() {
        initComponents ();
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jLabel1 = new javax.swing.JLabel();
        getContentPane().setLayout(new java.awt.GridLayout(2, 1));
        setName("GifDisplay");
        setTitle("CS456 Project 1 - Display GIFs");
        setFont(new java.awt.Font ("Garamond", 0, 12));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        }
        );
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        }
        );
        
        jLabel1.setAlignmentX(0.5F);
        jLabel1.setText("CS456 Project 1 - GIF Display");
        jLabel1.setForeground(new java.awt.Color (0, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setFont(new java.awt.Font ("Garamond", 0, 36));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        
        getContentPane().add(jLabel1);
        
        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setSize(new java.awt.Dimension(608, 639));
        setLocation((screenSize.width-608)/2,(screenSize.height-639)/2);
    }//GEN-END:initComponents
    
  private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
      this.setTitle("CS456 Project 1 - Display GIFs X=" + this.getWidth() + " Y=" + this.getHeight());
  }//GEN-LAST:event_formComponentResized
  
  private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
      
  }//GEN-LAST:event_formPropertyChange
  
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit (0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main (String args[]) {
        GifMain mainForm = new GifMain ();
        mainForm.getContentPane().add(new HelloWorldBean(args[0]));
        mainForm.show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
}
