/*
 * Convolution1D.java
 *
 * Created on February 20, 2001, 2:00 PM
 */
 
import jigl.signal.*;
import jigl.signal.io.*;
import javax.swing.*;
import java.io.*;
import jigl.signal.ops.levelOps.*;
/** 
 *
 * @author  bhinton
 * @version 
 */
public class Convolution1D extends javax.swing.JFrame {

  float[] testInput = {0,1,2,3,5,6,7,8,9};
  float[] testImpulse = {1,2,3};
  RealSignal input, output, impulse;
  /** Creates new form Convolution1D */
  public Convolution1D() {
    initComponents ();
    signalCanvas1 = new jigl.gui.SignalCanvas();
    signalCanvas2 = new jigl.gui.SignalCanvas();
    signalCanvas3 = new jigl.gui.SignalCanvas();
    jPanel1.add(signalCanvas1);
    jPanel3.add(signalCanvas2);
    jPanel4.add(signalCanvas3);
  
  }
     
  private Signal readFromFile(String filename) {
      Signal input;
      try {
        SignalInputStream is = new SignalInputStream(filename);
        input = is.read();
        is.close();
        return input;
      }
      catch (Exception e) {
        return null;
      }
  }
   private void writeToFile(Signal mySignal, String filename) {
      try {
        SignalOutputStream ios = new SignalOutputStream(filename);
        ios.write(mySignal);
        ios.close();
      }
      catch (Exception e) {
        JOptionPane.showMessageDialog(null, e.getMessage());
      }
      
  }
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the FormEditor.
   */
  private void initComponents() {//GEN-BEGIN:initComponents
      jPanel1 = new javax.swing.JPanel();
      jPanel3 = new javax.swing.JPanel();
      jPanel4 = new javax.swing.JPanel();
      jButton1 = new javax.swing.JButton();
      jButton2 = new javax.swing.JButton();
      jPanel2 = new javax.swing.JPanel();
      jButton5 = new javax.swing.JButton();
      jButton7 = new javax.swing.JButton();
      jButton6 = new javax.swing.JButton();
      getContentPane().setLayout(new java.awt.GridBagLayout());
      java.awt.GridBagConstraints gridBagConstraints1;
      addWindowListener(new java.awt.event.WindowAdapter() {
          public void windowClosing(java.awt.event.WindowEvent evt) {
              exitForm(evt);
          }
      }
      );
      
      jPanel1.setLayout(new java.awt.GridLayout(1, 1));
      jPanel1.setPreferredSize(new java.awt.Dimension(172, 463));
      jPanel1.setBorder(new javax.swing.border.TitledBorder("Input Signal Border"));
      
      gridBagConstraints1 = new java.awt.GridBagConstraints();
      gridBagConstraints1.gridx = 0;
      gridBagConstraints1.gridy = 0;
      gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
      gridBagConstraints1.weightx = 1.0;
      gridBagConstraints1.weighty = 80.0;
      getContentPane().add(jPanel1, gridBagConstraints1);
      
      
      jPanel3.setLayout(new java.awt.GridLayout(1, 1));
      jPanel3.setPreferredSize(new java.awt.Dimension(172, 463));
      jPanel3.setBorder(new javax.swing.border.TitledBorder("Impulse Signal"));
      
      gridBagConstraints1 = new java.awt.GridBagConstraints();
      gridBagConstraints1.gridx = 1;
      gridBagConstraints1.gridy = 0;
      gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
      gridBagConstraints1.weightx = 1.0;
      gridBagConstraints1.weighty = 80.0;
      getContentPane().add(jPanel3, gridBagConstraints1);
      
      
      jPanel4.setLayout(new java.awt.GridLayout(1, 1));
      jPanel4.setPreferredSize(new java.awt.Dimension(172, 463));
      jPanel4.setBorder(new javax.swing.border.TitledBorder("Output Signal Border"));
      
      gridBagConstraints1 = new java.awt.GridBagConstraints();
      gridBagConstraints1.gridx = 2;
      gridBagConstraints1.gridy = 0;
      gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
      gridBagConstraints1.weightx = 1.0;
      gridBagConstraints1.weighty = 80.0;
      getContentPane().add(jPanel4, gridBagConstraints1);
      
      
      jButton1.setText("Load Input");
      jButton1.addActionListener(new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
              jButton1ActionPerformed(evt);
          }
      }
      );
      
      gridBagConstraints1 = new java.awt.GridBagConstraints();
      gridBagConstraints1.gridx = 0;
      gridBagConstraints1.gridy = 1;
      gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
      gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
      gridBagConstraints1.weightx = 1.0;
      gridBagConstraints1.weighty = 1.0;
      getContentPane().add(jButton1, gridBagConstraints1);
      
      
      jButton2.setText("Load Impulse");
      jButton2.addActionListener(new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
              jButton2ActionPerformed(evt);
          }
      }
      );
      
      gridBagConstraints1 = new java.awt.GridBagConstraints();
      gridBagConstraints1.gridx = 1;
      gridBagConstraints1.gridy = 1;
      gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
      gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
      gridBagConstraints1.weightx = 1.0;
      gridBagConstraints1.weighty = 1.0;
      getContentPane().add(jButton2, gridBagConstraints1);
      
      
      jPanel2.setLayout(new java.awt.GridLayout(1, 3));
      
      jButton5.setText("Convolute");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        }
        );
        jPanel2.add(jButton5);
        
        
      jButton7.setText("Edge Enhancement");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        }
        );
        jPanel2.add(jButton7);
        
        
      jButton6.setText("Save Signal");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        }
        );
        jPanel2.add(jButton6);
        
        
      gridBagConstraints1 = new java.awt.GridBagConstraints();
      gridBagConstraints1.gridx = 2;
      gridBagConstraints1.gridy = 1;
      gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
      gridBagConstraints1.anchor = java.awt.GridBagConstraints.NORTHWEST;
      gridBagConstraints1.weightx = 1.0;
      gridBagConstraints1.weighty = 1.0;
      getContentPane().add(jPanel2, gridBagConstraints1);
      
      pack();
      java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
      java.awt.Dimension dialogSize = getSize();
      setSize(new java.awt.Dimension(700, 700));
      setLocation((screenSize.width-700)/2,(screenSize.height-700)/2);
  }//GEN-END:initComponents

  private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
    if (input != null && impulse != null)  output = edgeEnhancement(input, impulse);
    if (output == null) {
        JOptionPane.showMessageDialog(null, "The output was a null value");
        return;
    }
    else {
        output.byteSize();
    }
   try {
        signalCanvas3.setSignal(output);
        signalCanvas3.repaint();
    }
    catch (Exception e) {
        output = null;
        JOptionPane.showMessageDialog(null, "The error was " + e.getMessage());
    }
  }//GEN-LAST:event_jButton7ActionPerformed

  private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
      if (output != null) {
        String filename =  JOptionPane.showInputDialog(null, "Input a filename");
        writeToFile(output, filename);
      }
  }//GEN-LAST:event_jButton6ActionPerformed

  private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    if (input != null && impulse != null)  output = performConvolution(input, impulse);
   output.byteSize();
   try {
        signalCanvas3.setSignal(output);
        signalCanvas3.repaint();
    }
    catch (Exception e) {
        output = null;
    }
  }//GEN-LAST:event_jButton5ActionPerformed

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    String file = ImageFileBrowse();
    impulse = (RealSignal) readFromFile(file);
    impulse.byteSize();
    try {
        signalCanvas2.setSignal(impulse);
        signalCanvas2.repaint();
    }
    catch (Exception e) {
        impulse = null;
    }
  }//GEN-LAST:event_jButton2ActionPerformed

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String file = ImageFileBrowse();
    input = (RealSignal) readFromFile(file);
    input.byteSize();
    try {
        signalCanvas1.setSignal(input);
        signalCanvas1.repaint();
    }
    catch (Exception e) {
        input = null;
    }
  }//GEN-LAST:event_jButton1ActionPerformed

  private RealSignal performConvolution(RealSignal in,RealSignal im) {
    RealSignal out = new RealSignal(in.length() + im.length() -1);
     int i, j;
    float total;
    float[] inputArray, impulseArray;
    inputArray = in.getData();
    impulseArray = im.getData();
    for (i=0; i<out.length(); i++) {
      total = 0;
      for (j=0; j<= i; j++) {
        if (j < in.length() && (i-j) < im.length()) {
          total += inputArray[j] * impulseArray[i-j]; 
        }
      }
      out.set(i, total);
    }
    /*for (i=0; i< out.length(); i++) {
      JOptionPane.showMessageDialog(null, "The value at location output[" + i + "]=" + output.get(i));  
    }*/
   return out;
  }
  private RealSignal edgeEnhancement(RealSignal in,RealSignal im) {
    RealSignal out = new RealSignal(in.length() + im.length() -1);
    RealSignal temp;
    int i, j;
    float total;
    float[] inputArray, impulseArray;
    temp = (RealSignal) in.copy();
    temp.multiply(2);
    in.convolve(im);
    temp.subtract(in);
    try{
    (new jigl.signal.ops.levelOps.Scale(0, 2)).apply(temp);
    }
    catch (Exception e) {}
   return temp;
  }
  private String ImageFileBrowse() {
       File file;
      String name;
      JFileChooser selectFile = new JFileChooser();
      selectFile.showDialog(this, "Select File");
      file = selectFile.getSelectedFile();
      if (file != null) {
          return file.getAbsolutePath();
      }
      return "";
  }
  /** Exit the Application */
  private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
    System.exit (0);
  }//GEN-LAST:event_exitForm

  /**
  * @param args the command line arguments
  */
  public static void main (String args[]) {
    new Convolution1D ().show ();
  }

  private jigl.gui.SignalCanvas signalCanvas1;
  private jigl.gui.SignalCanvas signalCanvas2;
  private jigl.gui.SignalCanvas signalCanvas3;

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JButton jButton5;
  private javax.swing.JButton jButton7;
  private javax.swing.JButton jButton6;
  // End of variables declaration//GEN-END:variables

}