/*
 * CharacterDrawView.java
 *
 * Created on March 17, 2001, 2:40 PM
 */
import javax.swing.*;
import java.awt.Graphics;
/**
 *
 * @author  Bryan
 * @version 
 */
public class CharacterDrawView extends javax.swing.JFrame {

    /** Creates new form CharacterDrawView */
    public CharacterDrawView(CharacterModel c) {
        initComponents ();
        characterDraw1.setEditable(true);
        characterDraw1.setCharacterModel(c);
        cmdDraw.setSelected(true);
        cmdGreen.setSelected(true);
        this.setTitle("Character Draw View for " + c.getName());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cmdDraw = new javax.swing.JToggleButton();
        cmdSelect = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        cmdRed = new javax.swing.JToggleButton();
        cmdBlack = new javax.swing.JToggleButton();
        cmdGray = new javax.swing.JToggleButton();
        cmdPink = new javax.swing.JToggleButton();
        cmdOrange = new javax.swing.JToggleButton();
        cmdYellow = new javax.swing.JToggleButton();
        cmdGreen = new javax.swing.JToggleButton();
        cmdWhite = new javax.swing.JToggleButton();
        cmdBlue = new javax.swing.JToggleButton();
        cmdPurple = new javax.swing.JToggleButton();
        jPanel6 = new javax.swing.JPanel();
        characterDraw1 = new CharacterDraw();
        getContentPane().setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints1;
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        }
        );
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        }
        );
        
        jPanel1.setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints2;
        
        jPanel2.setLayout(new java.awt.GridLayout(1, 2));
          jPanel2.setPreferredSize(new java.awt.Dimension(142, 87));
          jPanel2.setBorder(new javax.swing.border.TitledBorder("Mode"));
          
          cmdDraw.setText("Draw");
            cmdDraw.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    cmdDrawActionPerformed(evt);
                }
            }
            );
            jPanel2.add(cmdDraw);
            
            
          cmdSelect.setText("Select");
            cmdSelect.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    cmdSelectActionPerformed(evt);
                }
            }
            );
            jPanel2.add(cmdSelect);
            
            gridBagConstraints2 = new java.awt.GridBagConstraints();
          gridBagConstraints2.fill = java.awt.GridBagConstraints.BOTH;
          gridBagConstraints2.anchor = java.awt.GridBagConstraints.WEST;
          gridBagConstraints2.weightx = 1.0;
          gridBagConstraints2.weighty = 1.0;
          jPanel1.add(jPanel2, gridBagConstraints2);
          
          
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 1;
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints1.weightx = 1.0;
        gridBagConstraints1.weighty = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints1);
        
        
        jPanel3.setLayout(new java.awt.GridLayout(2, 5));
        jPanel3.setBorder(new javax.swing.border.TitledBorder("Color Palette"));
        
        cmdRed.setBackground(java.awt.Color.red);
          cmdRed.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
          cmdRed.setMinimumSize(new java.awt.Dimension(1, 1));
          cmdRed.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
                  cmdRedActionPerformed(evt);
              }
          }
          );
          jPanel3.add(cmdRed);
          
          
        cmdBlack.setBackground(java.awt.Color.black);
          cmdBlack.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
          cmdBlack.setMinimumSize(new java.awt.Dimension(1, 1));
          cmdBlack.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
                  cmdRedActionPerformed(evt);
              }
          }
          );
          jPanel3.add(cmdBlack);
          
          
        cmdGray.setBackground(java.awt.Color.gray);
          cmdGray.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
          cmdGray.setMinimumSize(new java.awt.Dimension(1, 1));
          cmdGray.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
                  cmdRedActionPerformed(evt);
              }
          }
          );
          jPanel3.add(cmdGray);
          
          
        cmdPink.setBackground(java.awt.Color.pink);
          cmdPink.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
          cmdPink.setMinimumSize(new java.awt.Dimension(1, 1));
          cmdPink.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
                  cmdRedActionPerformed(evt);
              }
          }
          );
          jPanel3.add(cmdPink);
          
          
        cmdOrange.setBackground(java.awt.Color.orange);
          cmdOrange.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
          cmdOrange.setMinimumSize(new java.awt.Dimension(1, 1));
          cmdOrange.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
                  cmdRedActionPerformed(evt);
              }
          }
          );
          jPanel3.add(cmdOrange);
          
          
        cmdYellow.setPreferredSize(new java.awt.Dimension(105, 27));
          cmdYellow.setMaximumSize(new java.awt.Dimension(105, 27));
          cmdYellow.setBackground(java.awt.Color.yellow);
          cmdYellow.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
          cmdYellow.setMinimumSize(new java.awt.Dimension(1, 1));
          cmdYellow.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
                  cmdRedActionPerformed(evt);
              }
          }
          );
          jPanel3.add(cmdYellow);
          
          
        cmdGreen.setPreferredSize(new java.awt.Dimension(105, 27));
          cmdGreen.setMaximumSize(new java.awt.Dimension(105, 27));
          cmdGreen.setBackground(java.awt.Color.green);
          cmdGreen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
          cmdGreen.setMinimumSize(new java.awt.Dimension(1, 1));
          cmdGreen.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
                  cmdRedActionPerformed(evt);
              }
          }
          );
          jPanel3.add(cmdGreen);
          
          
        cmdWhite.setPreferredSize(new java.awt.Dimension(105, 27));
          cmdWhite.setMaximumSize(new java.awt.Dimension(105, 27));
          cmdWhite.setActionCommand("cmdCyan");
          cmdWhite.setBackground(java.awt.Color.white);
          cmdWhite.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
          cmdWhite.setMinimumSize(new java.awt.Dimension(1, 1));
          cmdWhite.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
                  cmdRedActionPerformed(evt);
              }
          }
          );
          jPanel3.add(cmdWhite);
          
          
        cmdBlue.setPreferredSize(new java.awt.Dimension(105, 27));
          cmdBlue.setMaximumSize(new java.awt.Dimension(105, 27));
          cmdBlue.setBackground(java.awt.Color.blue);
          cmdBlue.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
          cmdBlue.setMinimumSize(new java.awt.Dimension(1, 1));
          cmdBlue.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
                  cmdRedActionPerformed(evt);
              }
          }
          );
          jPanel3.add(cmdBlue);
          
          
        cmdPurple.setPreferredSize(new java.awt.Dimension(105, 27));
          cmdPurple.setMaximumSize(new java.awt.Dimension(105, 27));
          cmdPurple.setBackground(java.awt.Color.magenta);
          cmdPurple.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
          cmdPurple.setMinimumSize(new java.awt.Dimension(1, 1));
          cmdPurple.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
                  cmdRedActionPerformed(evt);
              }
          }
          );
          jPanel3.add(cmdPurple);
          
          
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 1;
        gridBagConstraints1.gridy = 1;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints1.weightx = 70.0;
        gridBagConstraints1.weighty = 1.0;
        getContentPane().add(jPanel3, gridBagConstraints1);
        
        
        jPanel6.setLayout(new java.awt.FlowLayout(0, 5, 5));
        jPanel6.setBorder(new javax.swing.border.TitledBorder("Canvas"));
        jPanel6.setMaximumSize(new java.awt.Dimension(212, 227));
        
        characterDraw1.setEnableEditing(true);
          characterDraw1.setBackground(java.awt.Color.white);
          characterDraw1.setMaximumSize(new java.awt.Dimension(200, 200));
          jPanel6.add(characterDraw1);
          
          
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 0;
        gridBagConstraints1.gridwidth = 2;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints1.weightx = 1.0;
        gridBagConstraints1.weighty = 80.0;
        getContentPane().add(jPanel6, gridBagConstraints1);
        
        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setSize(new java.awt.Dimension(450, 350));
        setLocation((screenSize.width-450)/2,(screenSize.height-350)/2);
    }//GEN-END:initComponents

  private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
      if (evt.getKeyCode() == evt.VK_DELETE) {
        characterDraw1.deleteSelected();
      }
  }//GEN-LAST:event_formKeyPressed

  private void cmdRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRedActionPerformed
    ClearButtons();
    ((JToggleButton) evt.getSource()).setSelected(true);
    characterDraw1.setCurColor(((JToggleButton) evt.getSource()).getBackground());
    repaint();
  }//GEN-LAST:event_cmdRedActionPerformed

  private void ClearButtons() {
    cmdBlue.setSelected(false);
    cmdWhite.setSelected(false);
    cmdPurple.setSelected(false);
    cmdGreen.setSelected(false);
    cmdYellow.setSelected(false);
    cmdOrange.setSelected(false);
    cmdPink.setSelected(false);
    cmdGray.setSelected(false);
    cmdBlack.setSelected(false);
    cmdRed.setSelected(false);
  }
  private void cmdSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSelectActionPerformed
      if (cmdSelect.isSelected()) {
          cmdDraw.setSelected(false);
          characterDraw1.setEnableSelecting(true);
      }
      else characterDraw1.setEnableSelecting(false);
  }//GEN-LAST:event_cmdSelectActionPerformed

  private void cmdDrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDrawActionPerformed
      if (cmdDraw.isSelected()) { 
          cmdSelect.setSelected(false);
          characterDraw1.setEnableEditing(true);
      }
      else characterDraw1.setEnableEditing(false);
  }//GEN-LAST:event_cmdDrawActionPerformed

  public void paint(Graphics g) {
    super.paint(g);
    jPanel6.setBorder(new javax.swing.border.TitledBorder("Canvas - Size is " + characterDraw1.getWidth() + ", " + characterDraw1.getHeight()));
    jPanel3.setBorder(new javax.swing.border.TitledBorder("Color Palette - " + characterDraw1.getCurColor()));
  }
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        this.dispose();
    }//GEN-LAST:event_exitForm

    public static void main(String args[]) {
        new CharacterDrawView(new CharacterModel()).setVisible(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton cmdDraw;
    private javax.swing.JToggleButton cmdSelect;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToggleButton cmdRed;
    private javax.swing.JToggleButton cmdBlack;
    private javax.swing.JToggleButton cmdGray;
    private javax.swing.JToggleButton cmdPink;
    private javax.swing.JToggleButton cmdOrange;
    private javax.swing.JToggleButton cmdYellow;
    private javax.swing.JToggleButton cmdGreen;
    private javax.swing.JToggleButton cmdWhite;
    private javax.swing.JToggleButton cmdBlue;
    private javax.swing.JToggleButton cmdPurple;
    private javax.swing.JPanel jPanel6;
    private CharacterDraw characterDraw1;
    // End of variables declaration//GEN-END:variables

}
