/*
 * CharacterView.java
 *
 * Created on February 3, 2001, 1:05 PM
 */


/**
 *
 * @author  Bryan
 * @version 
 */
import java.awt.*;
import java.beans.*;
import javax.swing.*;
import java.io.*;
public class CharacterView extends javax.swing.JFrame {

    private CharacterModel cm;
    private String searchDirectory;
    private PropertyChangeListener pcl;
    /** Creates new form CharacterView */
    public CharacterView(CharacterModel cmodel, String search) {
        cm= cmodel;
        initComponents ();
        updateFields();
        addMyListeners();
        searchDirectory = search;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtStrength = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        cmdClose = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        characterDraw1 = new CharacterDraw();
        jPanel6 = new javax.swing.JPanel();
        getContentPane().setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints1;
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        }
        );
        
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, 1));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 87));
        jPanel1.setBorder(new javax.swing.border.TitledBorder(
        new javax.swing.border.EtchedBorder(), "Edit View", 4, 2,
        new java.awt.Font ("Garamond", 1, 12)));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 87));
        
        jPanel3.setLayout(new java.awt.GridBagLayout());
          java.awt.GridBagConstraints gridBagConstraints2;
          
          jLabel4.setText("Character Name");
            jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            jLabel4.setRequestFocusEnabled(false);
            jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
            gridBagConstraints2 = new java.awt.GridBagConstraints();
            gridBagConstraints2.gridwidth = -1;
            gridBagConstraints2.gridheight = -1;
            gridBagConstraints2.anchor = java.awt.GridBagConstraints.WEST;
            gridBagConstraints2.weightx = 1.0;
            gridBagConstraints2.weighty = 1.0;
            jPanel3.add(jLabel4, gridBagConstraints2);
            
            
          txtName.setToolTipText("Enter the character's name");
            txtName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            txtName.addFocusListener(new java.awt.event.FocusAdapter() {
                public void focusLost(java.awt.event.FocusEvent evt) {
                    txtNameFocusLost(evt);
                }
            }
            );
            txtName.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    txtNameKeyPressed(evt);
                }
            }
            );
            gridBagConstraints2 = new java.awt.GridBagConstraints();
            gridBagConstraints2.gridwidth = -1;
            gridBagConstraints2.gridheight = -1;
            gridBagConstraints2.fill = java.awt.GridBagConstraints.HORIZONTAL;
            gridBagConstraints2.insets = new java.awt.Insets(0, 23, 0, 0);
            gridBagConstraints2.anchor = java.awt.GridBagConstraints.WEST;
            gridBagConstraints2.weightx = 80.0;
            gridBagConstraints2.weighty = 1.0;
            jPanel3.add(txtName, gridBagConstraints2);
            
            jPanel1.add(jPanel3);
          
          
        jPanel4.setLayout(new java.awt.GridBagLayout());
          java.awt.GridBagConstraints gridBagConstraints3;
          
          jLabel5.setText("Character Strength");
            jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            jLabel5.setRequestFocusEnabled(false);
            jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
            gridBagConstraints3 = new java.awt.GridBagConstraints();
            gridBagConstraints3.gridwidth = -1;
            gridBagConstraints3.gridheight = -1;
            gridBagConstraints3.anchor = java.awt.GridBagConstraints.WEST;
            gridBagConstraints3.weightx = 1.0;
            gridBagConstraints3.weighty = 1.0;
            jPanel4.add(jLabel5, gridBagConstraints3);
            
            
          txtStrength.setToolTipText("Enter the character's strength");
            txtStrength.addFocusListener(new java.awt.event.FocusAdapter() {
                public void focusLost(java.awt.event.FocusEvent evt) {
                    txtStrengthFocusLost(evt);
                }
            }
            );
            txtStrength.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    txtStrengthKeyPressed(evt);
                }
            }
            );
            gridBagConstraints3 = new java.awt.GridBagConstraints();
            gridBagConstraints3.gridwidth = -1;
            gridBagConstraints3.gridheight = -1;
            gridBagConstraints3.fill = java.awt.GridBagConstraints.HORIZONTAL;
            gridBagConstraints3.insets = new java.awt.Insets(0, 8, 0, 0);
            gridBagConstraints3.anchor = java.awt.GridBagConstraints.WEST;
            gridBagConstraints3.weightx = 80.0;
            gridBagConstraints3.weighty = 1.0;
            jPanel4.add(txtStrength, gridBagConstraints3);
            
            jPanel1.add(jPanel4);
          
          
        jPanel7.setLayout(new java.awt.FlowLayout(1, 0, 0));
          jPanel7.setPreferredSize(new java.awt.Dimension(105, 30));
          jPanel7.setMinimumSize(new java.awt.Dimension(105, 30));
          
          cmdClose.setText("Close");
            cmdClose.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    cmdCloseActionPerformed(evt);
                }
            }
            );
            cmdClose.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    cmdCloseKeyPressed(evt);
                }
            }
            );
            jPanel7.add(cmdClose);
            
            jPanel1.add(jPanel7);
          
          
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 0;
        gridBagConstraints1.gridheight = -1;
        gridBagConstraints1.ipady = 50;
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints1.weightx = 1.0;
        gridBagConstraints1.weighty = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints1);
        
        
        jPanel2.setLayout(new java.awt.GridLayout(1, 3));
        jPanel2.setPreferredSize(new java.awt.Dimension(218, 218));
        jPanel2.setBorder(new javax.swing.border.TitledBorder(
        new javax.swing.border.EtchedBorder(), "Image View", 4, 2,
        new java.awt.Font ("Garamond", 1, 12)));
        jPanel2.setMinimumSize(new java.awt.Dimension(218, 218));
        jPanel2.setMaximumSize(new java.awt.Dimension(32779, 98328));
        
        jPanel5.setPreferredSize(new java.awt.Dimension(200, 135));
          jPanel5.setMinimumSize(new java.awt.Dimension(200, 135));
          jPanel5.setBackground(java.awt.Color.white);
          jPanel5.setMaximumSize(new java.awt.Dimension(200, 135));
          jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
              public void mouseClicked(java.awt.event.MouseEvent evt) {
                  characterDraw1MouseClicked(evt);
              }
          }
          );
          jPanel2.add(jPanel5);
          
          
        characterDraw1.setMinimumSize(new java.awt.Dimension(200, 200));
          characterDraw1.setCharacterModel(this.cm);
          characterDraw1.setBackground(java.awt.Color.white);
          characterDraw1.setMaximumSize(new java.awt.Dimension(200, 200));
          characterDraw1.addMouseListener(new java.awt.event.MouseAdapter() {
              public void mouseClicked(java.awt.event.MouseEvent evt) {
                  characterDraw1MouseClicked(evt);
              }
          }
          );
          jPanel2.add(characterDraw1);
          
          
        jPanel6.setPreferredSize(new java.awt.Dimension(200, 135));
          jPanel6.setMinimumSize(new java.awt.Dimension(200, 135));
          jPanel6.setBackground(java.awt.Color.white);
          jPanel6.setMaximumSize(new java.awt.Dimension(200, 135));
          jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
              public void mouseClicked(java.awt.event.MouseEvent evt) {
                  characterDraw1MouseClicked(evt);
              }
          }
          );
          jPanel2.add(jPanel6);
          
          
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 1;
        gridBagConstraints1.gridwidth = 2;
        gridBagConstraints1.gridheight = -1;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints1.weightx = 10.0;
        gridBagConstraints1.weighty = 80.0;
        getContentPane().add(jPanel2, gridBagConstraints1);
        
        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setSize(new java.awt.Dimension(600, 470));
        setLocation((screenSize.width-600)/2,(screenSize.height-470)/2);
    }//GEN-END:initComponents

  private void characterDraw1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_characterDraw1MouseClicked
    (new CharacterDrawView(this.cm)).setVisible(true);
  }//GEN-LAST:event_characterDraw1MouseClicked

  private void cmdCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCloseActionPerformed
    removeMyListeners();
    this.dispose();
  }//GEN-LAST:event_cmdCloseActionPerformed

  private void txtStrengthFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtStrengthFocusLost
    saveModel();
  }//GEN-LAST:event_txtStrengthFocusLost

  private void txtStrengthKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStrengthKeyPressed
    if (evt.getKeyCode() == evt.VK_ENTER) saveModel();
  }//GEN-LAST:event_txtStrengthKeyPressed

  private void txtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyPressed
    if (evt.getKeyCode() == evt.VK_ENTER) saveModel();
  }//GEN-LAST:event_txtNameKeyPressed

  private void txtNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusLost
    saveModel();
  }//GEN-LAST:event_txtNameFocusLost

  private void cmdCloseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmdCloseKeyPressed
    removeMyListeners();
    this.dispose();
  }//GEN-LAST:event_cmdCloseKeyPressed
  private void saveModel() {
        if (txtName.getText().equals(cm.getName()) == false) {
        cm.setName(txtName.getText());
      }
      if (txtStrength.getText().equals(String.valueOf(cm.getStrength())) == false) {
          try {
            cm.setStrength((new Integer(txtStrength.getText())).intValue());
          }
          catch (NumberFormatException ne) {
            JOptionPane.showMessageDialog(null, "Invalid Strength value", "Invalid Number", JOptionPane.ERROR_MESSAGE); 
          }
      }
  }
 
  public void paint(Graphics g) {
    Image temp;
    super.paint(g);
    this.setTitle("Character View for " + cm.getName());
    updateFields();
  }
  private void updateFields() {
      if (cm != null) {  
        txtName.setText(cm.getName());
        txtStrength.setText(String.valueOf(cm.getStrength()));
      }
  }
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        removeMyListeners();
        this.dispose();
    }//GEN-LAST:event_exitForm

     private void addMyListeners() {
        cm.addPropertyChangeListener(pcl = new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                modelChanged(evt);
            }
        });
    }
    private void modelChanged(java.beans.PropertyChangeEvent evt) {
        repaint();
    }
    private void removeMyListeners() {
        cm.removePropertyChangeListener(pcl);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtName;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtStrength;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JButton cmdClose;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private CharacterDraw characterDraw1;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables

}
